on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      extension:
        type: string
        default: "jsonl"

jobs:
  process-results:
    runs-on: ubuntu-latest
    env:
      NAME: ${{ inputs.name }}
      EXTENSION: ${{ inputs.extension }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: latest-result
          path: ./
      - name: Replace with latest result
        run: |
          rm -rf results/$NAME/latest.$EXTENSION
          mv latest.$EXTENSION results/$NAME
      - name: Process results
        run: |
          FILENAME=$(date +%Y-%m-%d)
          cd results/$NAME
          cp latest.$EXTENSION $FILENAME.$EXTENSION
          gzip $FILENAME.$EXTENSION
      - name: Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add results/$NAME
          git commit -m "ci: $NAME suite results"
          git push
